import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';
import { jsPDF } from 'npm:jspdf@4.0.0';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { to, subject, body, participant_name } = await req.json();
    
    if (!to || !subject || !body) {
      return Response.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // Create simple PDF from text content
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    const maxWidth = pageWidth - 2 * margin;

    // Strip HTML tags and convert to plain text
    const plainText = body.replace(/<[^>]*>/g, '').trim();
    
    let yPosition = margin;

    // Add header
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Impact Vault Report', margin, yPosition);
    yPosition += 12;
    doc.setFont(undefined, 'normal');

    // Add content as plain text with wrapping
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(plainText, maxWidth);
    
    lines.forEach((line) => {
      if (yPosition > pageHeight - margin - 5) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line, margin, yPosition);
      yPosition += 5;
    });

    // Add footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Impact Vault · Confidential', margin, pageHeight - 5);

    const pdfBytes = doc.output('arraybuffer');

    // Create email body with report content
    const emailBody = `
      <html>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1c1917; line-height: 1.6;">
          <div style="background-color: #f5f4f0; border-left: 4px solid #b6ada5; padding: 16px; margin-bottom: 24px; border-radius: 4px;">
            <p style="margin: 0 0 8px 0; font-size: 13px; font-weight: 600; color: #7a726c;">📄 Report Ready</p>
            <p style="margin: 0; font-size: 12px; color: #8f8784;">Your Impact Vault report has been generated. View the formatted version in your Impact Vault dashboard for the best experience with charts and visualizations.</p>
          </div>
          ${body}
          <div style="margin-top: 32px; padding-top: 16px; border-top: 1px solid #e7e5e4;">
            <p style="font-size: 12px; color: #a8a29e; margin: 0;">
              Generated by Impact Vault · Confidential
            </p>
          </div>
        </body>
      </html>
    `;

    // Send email (use service role to allow sending to any email address)
    await base44.asServiceRole.integrations.Core.SendEmail({
      to,
      subject,
      body: emailBody,
      from_name: 'Impact Vault'
    });

    return Response.json({ success: true });
  } catch (error) {
    console.error('Error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});